window.DASHBOARD_DATA = {
  "generatedAt": "2026-07-20T10:35:45+00:00",
  "reportFolder": "sample-reports (demo data - run scripts\\Update-Dashboard.ps1 to use your real folders)",
  "reports": [
    {
      "file": "seadrill-report_Fleet_2026-07-13.json",
      "rig": "Fleet",
      "reporttype": "BWM Weekly Planning",
      "type": "N/A",
      "discipline": "Planning",
      "wce": "Bo Sherman",
      "location": "Fleet-wide",
      "date": "2026-07-13",
      "dateEnd": "",
      "exportedAt": "07/13/2026 12:00:00",
      "modified": "2026-07-16T14:45:13",
      "tileCount": 1,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Auriga_2026-07-10_rapid-53-s53-event-report.json",
      "rig": "West Auriga",
      "reporttype": "Rapid 53 (S53 Event Report)",
      "type": "",
      "discipline": "",
      "wce": "On duty",
      "location": "GoM - Tiber",
      "date": "2026-07-10",
      "dateEnd": "",
      "exportedAt": "07/10/2026 18:00:00",
      "modified": "2026-07-20T10:33:32",
      "tileCount": 1,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Gemini_2026-07-09.json",
      "rig": "West Gemini",
      "reporttype": "Rig Visit",
      "type": "BWM Compliance",
      "discipline": "Well Control (WCEG)",
      "wce": "M. Reyes",
      "location": "Angola Block 17",
      "date": "2026-07-09",
      "dateEnd": "2026-07-10",
      "exportedAt": "07/10/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 2,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 1,
      "actionsLeftWithRig": 1,
      "criticalItems": [],
      "actionItems": [
        {
          "desc": "Close out BWM checklist items 4 & 7",
          "sys": "BOP",
          "resp": "SSS",
          "target": "",
          "deadline": "2026-07-18",
          "leftWithRig": true
        }
      ]
    },
    {
      "file": "seadrill-report_Fleet_2026-07-06.json",
      "rig": "Fleet",
      "reporttype": "BWM Weekly Planning",
      "type": "N/A",
      "discipline": "Planning",
      "wce": "Bo Sherman",
      "location": "Fleet-wide",
      "date": "2026-07-06",
      "dateEnd": "",
      "exportedAt": "07/06/2026 12:00:00",
      "modified": "2026-07-16T14:45:13",
      "tileCount": 1,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Neptune_2026-07-06.json",
      "rig": "West Neptune",
      "reporttype": "Rig Visit",
      "type": "Operations Support",
      "discipline": "Well Control (WCEG)",
      "wce": "D. Plant",
      "location": "GoM — Shenandoah",
      "date": "2026-07-06",
      "dateEnd": "2026-07-08",
      "exportedAt": "07/08/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 3,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Capella_2026-07-05_cbm-inspection.json",
      "rig": "West Capella",
      "reporttype": "CBM Inspection",
      "type": "",
      "discipline": "",
      "wce": "D. Plant",
      "location": "PTTEP Malaysia",
      "date": "2026-07-05",
      "dateEnd": "",
      "exportedAt": "T17:30:00.000Z",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 1,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Tellus_2026-07-03.json",
      "rig": "West Tellus",
      "reporttype": "Rig Visit",
      "type": "NPT Support",
      "discipline": "Well Control (WCEG)",
      "wce": "M. Reyes",
      "location": "GoM — Kaskida",
      "date": "2026-07-03",
      "dateEnd": "2026-07-05",
      "exportedAt": "07/05/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 3,
      "criticalTotal": 1,
      "criticalOpen": 1,
      "actionsTotal": 1,
      "actionsLeftWithRig": 1,
      "criticalItems": [
        {
          "done": false,
          "equip": "Diverter Packer",
          "sfi": "312.02",
          "date": "2026-07-03",
          "issue": "Pressure test failed at 500 psi",
          "mit": "Packer replacement scheduled next trip out"
        }
      ],
      "actionItems": [
        {
          "desc": "Expedite diverter packer to rig",
          "sys": "Diverter",
          "resp": "Rig Mgr",
          "target": "",
          "deadline": "2026-07-12",
          "leftWithRig": true
        }
      ]
    },
    {
      "file": "seadrill-report_West-Capella_2026-06_daily-log.json",
      "rig": "West Capella",
      "reporttype": "Daily Log",
      "type": "",
      "discipline": "",
      "wce": "On duty",
      "location": "PTTEP Malaysia",
      "date": "2026-07-01",
      "dateEnd": "",
      "exportedAt": "07/01/2026 18:00:00",
      "modified": "2026-07-20T10:33:32",
      "tileCount": 0,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Neptune_2026-06_daily-log.json",
      "rig": "West Neptune",
      "reporttype": "Daily Log",
      "type": "",
      "discipline": "",
      "wce": "On duty",
      "location": "GoM - Shenandoah",
      "date": "2026-07-01",
      "dateEnd": "",
      "exportedAt": "07/01/2026 18:00:00",
      "modified": "2026-07-20T10:33:32",
      "tileCount": 0,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Saturn_2026-06-30.json",
      "rig": "West Saturn",
      "reporttype": "Rig Visit",
      "type": "Vendor Surveillance",
      "discipline": "Well Control (WCEG)",
      "wce": "D. Plant",
      "location": "Angola Block 15",
      "date": "2026-06-30",
      "dateEnd": "2026-07-02",
      "exportedAt": "07/02/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 3,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 1,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": [
        {
          "desc": "Verify vendor torque records for wellhead connector",
          "sys": "Wellhead",
          "resp": "TSL",
          "target": "",
          "deadline": "2026-07-08",
          "leftWithRig": false
        }
      ]
    },
    {
      "file": "seadrill-report_West-Auriga_2026-06-25.json",
      "rig": "West Auriga",
      "reporttype": "Rig Visit",
      "type": "Investigation",
      "discipline": "Well Control (WCEG)",
      "wce": "M. Reyes",
      "location": "GoM — Tiber",
      "date": "2026-06-25",
      "dateEnd": "2026-06-29",
      "exportedAt": "06/29/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 5,
      "criticalTotal": 3,
      "criticalOpen": 2,
      "actionsTotal": 2,
      "actionsLeftWithRig": 1,
      "criticalItems": [
        {
          "done": false,
          "equip": "Blue Pod SEM B",
          "sfi": "333.20",
          "date": "2026-06-25",
          "issue": "Intermittent comms fault",
          "mit": "Troubleshooting ongoing — pod on surface"
        },
        {
          "done": false,
          "equip": "LMRP Connector",
          "sfi": "333.15",
          "date": "2026-06-25",
          "issue": "Secondary unlock function failed test",
          "mit": "Function isolated, OEM engaged"
        },
        {
          "done": true,
          "equip": "Shear Ram Bonnet",
          "sfi": "333.05",
          "date": "2026-06-25",
          "issue": "Seal seep on function test",
          "mit": "Bonnet reseal complete"
        }
      ],
      "actionItems": [
        {
          "desc": "OEM RCA for SEM B comms fault",
          "sys": "MUX Controls",
          "resp": "WCE",
          "target": "",
          "deadline": "2026-07-20",
          "leftWithRig": false
        },
        {
          "desc": "Re-test LMRP secondary unlock after seal kit",
          "sys": "LMRP",
          "resp": "SSS",
          "target": "",
          "deadline": "2026-07-10",
          "leftWithRig": true
        }
      ]
    },
    {
      "file": "seadrill-report_Sevan-Louisiana_2026-06-22.json",
      "rig": "Sevan Louisiana",
      "reporttype": "Rig Visit",
      "type": "Operations Support",
      "discipline": "Well Control (WCEG)",
      "wce": "D. Plant",
      "location": "GoM — Salamanca",
      "date": "2026-06-22",
      "dateEnd": "2026-06-24",
      "exportedAt": "06/24/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 3,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 0,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": []
    },
    {
      "file": "seadrill-report_West-Vela_2026-06-18.json",
      "rig": "West Vela",
      "reporttype": "Rig Visit",
      "type": "Technical Inspection",
      "discipline": "Well Control (WCEG)",
      "wce": "M. Reyes",
      "location": "GoM — Whale",
      "date": "2026-06-18",
      "dateEnd": "2026-06-21",
      "exportedAt": "06/21/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 4,
      "criticalTotal": 0,
      "criticalOpen": 0,
      "actionsTotal": 1,
      "actionsLeftWithRig": 0,
      "criticalItems": [],
      "actionItems": [
        {
          "desc": "Recalibrate riser tensioner sensors",
          "sys": "Tensioners",
          "resp": "Elec Supv",
          "target": "",
          "deadline": "2026-07-01",
          "leftWithRig": false
        }
      ]
    },
    {
      "file": "seadrill-report_West-Neptune_2026-06-15.json",
      "rig": "West Neptune",
      "reporttype": "Rig Visit",
      "type": "BWM Compliance",
      "discipline": "Well Control (WCEG)",
      "wce": "D. Plant",
      "location": "GoM — Shenandoah",
      "date": "2026-06-15",
      "dateEnd": "2026-06-19",
      "exportedAt": "06/19/2026 17:30:00",
      "modified": "2026-07-16T14:44:30",
      "tileCount": 5,
      "criticalTotal": 1,
      "criticalOpen": 0,
      "actionsTotal": 1,
      "actionsLeftWithRig": 1,
      "criticalItems": [
        {
          "done": true,
          "equip": "Upper Annular",
          "sfi": "333.01",
          "date": "2026-06-15",
          "issue": "Element wear at limit",
          "mit": "Replaced on deck"
        }
      ],
      "actionItems": [
        {
          "desc": "Update annular PM interval",
          "sys": "BOP",
          "resp": "SSS",
          "target": "",
          "deadline": "2026-07-15",
          "leftWithRig": true
        }
      ]
    }
  ],
  "dailyLog": {
    "entries": [
      {
        "rig": "West Neptune",
        "month": "2026-06",
        "date": "2026-06-27",
        "equip": "HPU",
        "failure": false,
        "lesson": false,
        "note": "Changed out pump 2 suction filter on schedule.",
        "photos": 0,
        "file": "seadrill-report_West-Neptune_2026-06_daily-log.json"
      },
      {
        "rig": "West Neptune",
        "month": "2026-06",
        "date": "2026-06-21",
        "equip": "U2B Door",
        "failure": true,
        "lesson": true,
        "note": "Door seal extruded during test. Failure traced to incorrect seal durometer from stores. Lesson: verify seal part number against IPL before install - two visually identical seals in stock.",
        "photos": 0,
        "file": "seadrill-report_West-Neptune_2026-06_daily-log.json"
      },
      {
        "rig": "West Capella",
        "month": "2026-06",
        "date": "2026-06-19",
        "equip": "LMRP Connector",
        "failure": false,
        "lesson": true,
        "note": "Secondary unlock circuit slow to vent. Lesson: vent line loop traps fluid after washdown - added drain-down to post-wash checklist.",
        "photos": 0,
        "file": "seadrill-report_West-Capella_2026-06_daily-log.json"
      },
      {
        "rig": "West Neptune",
        "month": "2026-06",
        "date": "2026-06-14",
        "equip": "Riser Tensioners",
        "failure": false,
        "lesson": true,
        "note": "Found APV accumulator precharge drifting on unit 3. Lesson: check precharge weekly during heavy weather season, not monthly.",
        "photos": 0,
        "file": "seadrill-report_West-Neptune_2026-06_daily-log.json"
      },
      {
        "rig": "West Capella",
        "month": "2026-06",
        "date": "2026-06-12",
        "equip": "Yellow Pod",
        "failure": true,
        "lesson": false,
        "note": "Pod flow reading spiked during stump test; traced to partially blocked filter. Cleaned and retested OK.",
        "photos": 0,
        "file": "seadrill-report_West-Capella_2026-06_daily-log.json"
      },
      {
        "rig": "West Neptune",
        "month": "2026-06",
        "date": "2026-06-08",
        "equip": "Blue Pod SEM A",
        "failure": true,
        "lesson": false,
        "note": "Intermittent solenoid readback fault on function 12B. Cycled power, fault cleared; monitoring.",
        "photos": 0,
        "file": "seadrill-report_West-Neptune_2026-06_daily-log.json"
      },
      {
        "rig": "West Capella",
        "month": "2026-06",
        "date": "2026-06-05",
        "equip": "Diverter",
        "failure": false,
        "lesson": false,
        "note": "Diverter packer visual inspection - no findings.",
        "photos": 0,
        "file": "seadrill-report_West-Capella_2026-06_daily-log.json"
      },
      {
        "rig": "West Neptune",
        "month": "2026-06",
        "date": "2026-06-03",
        "equip": "Upper Annular",
        "failure": false,
        "lesson": false,
        "note": "Routine function test completed, all parameters nominal.",
        "photos": 0,
        "file": "seadrill-report_West-Neptune_2026-06_daily-log.json"
      }
    ],
    "r53Events": [
      {
        "rig": "West Auriga",
        "date": "2026-07-10",
        "equip": "Shuttle Valve",
        "item": "BOP Control Pod",
        "mfr": "NOV",
        "model": "M25",
        "obsfailure": "Fails to operate on demand",
        "malfunction": "Shuttle valve on pilot circuit 14 stuck mid-travel during stump testing, blocking function on both pods.",
        "rootcause": "Pilot filter element degraded beyond service limit.",
        "findings": "Scoring on shuttle bore consistent with particulate contamination.",
        "lessons": "Add pilot filter differential-pressure check to weekly PM; replace elements on calendar time not condition.",
        "source": "R53 Report",
        "file": "seadrill-report_West-Auriga_2026-07-10_rapid-53-s53-event-report.json"
      }
    ]
  }
};
